apiVersion: v2
description: Wrapper chart for the Nuxeo application on Google Cloud Marketplace
name: nuxeo-mp
version: 2.7.1
appVersion: 2025.13
dependencies:
  - name: nuxeo
    version: 3.1.23
    repository: https://packages.nuxeo.com/repository/helm-releases-public/
