apiVersion: v1
description: Wrapper chart for the Nuxeo application on Google Cloud Marketplace
name: nuxeo-mp
version: 2.4-SNAPSHOT
appVersion: 2025.10
dependencies:
  - name: nuxeo
    version: ~3.1.0
    repository: https://packages.nuxeo.com/repository/helm-releases-public/
